`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
/home/paperspace/.local/lib/python3.11/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b547ffd0>> (for post_run_cell), with arguments args (<ExecutionResult object at 7fa9954e2510, execution_count=8 error_before_exec=None error_in_exec= info=<ExecutionInfo object at 7fa96c321c50, raw_cell="import transformers
# needed for gpt-neo-x tokeni.." store_history=True silent=False shell_futures=True cell_id=None> result=None>,),kwargs {}:
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b547ffd0>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7fa4b27b5a10, raw_cell="import transformers
# needed for gpt-neo-x tokeni.." store_history=True silent=False shell_futures=True cell_id=None>,),kwargs {}:
max_steps is given, it will override any value given in num_train_epochs
/home/paperspace/.local/lib/python3.11/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b547ffd0>> (for post_run_cell), with arguments args (<ExecutionResult object at 7fa4b4adc810, execution_count=9 error_before_exec=None error_in_exec= info=<ExecutionInfo object at 7fa4b27b5a10, raw_cell="import transformers
# needed for gpt-neo-x tokeni.." store_history=True silent=False shell_futures=True cell_id=None> result=None>,),kwargs {}:
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b547ffd0>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7fa4b1de1990, raw_cell="import transformers
# needed for gpt-neo-x tokeni.." store_history=True silent=False shell_futures=True cell_id=None>,),kwargs {}:
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b547ffd0>> (for post_run_cell), with arguments args (<ExecutionResult object at 7fa4b27b5f90, execution_count=10 error_before_exec=None error_in_exec=PreTrainedModel.gradient_checkpointing_enable() got an unexpected keyword argument 'use_reentrant' info=<ExecutionInfo object at 7fa4b1de1990, raw_cell="import transformers
# needed for gpt-neo-x tokeni.." store_history=True silent=False shell_futures=True cell_id=None> result=None>,),kwargs {}:
/home/paperspace/.local/lib/python3.11/site-packages/transformers/training_args.py:1463: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
max_steps is given, it will override any value given in num_train_epochs
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b547ffd0>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7fa4ac28a610, raw_cell="!pip install wandb --upgrade" store_history=True silent=False shell_futures=True cell_id=None>,),kwargs {}:
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wandb in /home/paperspace/.local/lib/python3.11/site-packages (0.15.10)
Collecting wandb
  Downloading wandb-0.16.6-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: Click!=8.0.0,>=7.1 in /usr/lib/python3/dist-packages (from wandb) (8.0.3)
Requirement already satisfied: GitPython!=3.1.29,>=1.0.0 in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (3.1.40)
Requirement already satisfied: requests<3,>=2.0.0 in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (2.31.0)
Requirement already satisfied: psutil>=5.0.0 in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (5.9.6)
Requirement already satisfied: sentry-sdk>=1.0.0 in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (1.36.0)
Requirement already satisfied: docker-pycreds>=0.4.0 in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (0.4.0)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from wandb) (5.4.1)
Requirement already satisfied: setproctitle in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (1.3.3)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from wandb) (59.6.0)
Requirement already satisfied: appdirs>=1.4.3 in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (1.4.4)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in /home/paperspace/.local/lib/python3.11/site-packages (from wandb) (4.23.4)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/paperspace/.local/lib/python3.11/site-packages (from GitPython!=3.1.29,>=1.0.0->wandb) (4.0.11)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/paperspace/.local/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.0.0->wandb) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/paperspace/.local/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3,>=2.0.0->wandb) (2020.6.20)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/paperspace/.local/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->GitPython!=3.1.29,>=1.0.0->wandb) (5.0.1)
Downloading wandb-0.16.6-py3-none-any.whl (2.2 MB)
   [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[39m [32m2.2/2.2 MB[39m [31m36.8 MB/s[39m eta [36m0:00:00
[?25hInstalling collected packages: wandb
  Attempting uninstall: wandb
    Found existing installation: wandb 0.15.10
    Uninstalling wandb-0.15.10:
      Successfully uninstalled wandb-0.15.10
Successfully installed wandb-0.16.6
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fa4b547ffd0>> (for post_run_cell), with arguments args (<ExecutionResult object at 7fa4b1d02110, execution_count=11 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7fa4ac28a610, raw_cell="!pip install wandb --upgrade" store_history=True silent=False shell_futures=True cell_id=None> result=None>,),kwargs {}: